mybatis:
  typeAliasesPackage: com.website.dao.mappers
  mapperLocations: classpath:com/website/dao/mappers/*.xml
jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://catstudiotest.mysql.rds.aliyuncs.com:3306/nekostory_web?useUnicode=true&characterEncoding=UTF-8
  username: nekostoryweb
  password: NekoWeb123